sudo: required
services : 
  - docker 

before_install :
  - docker build -t ashishyete/dockerDemo -f Dockerfile .
  
language : java
jdk :
   -openjdk8
script: ./mvnw clean install

jobs: 
   include:
     - stage : test
       script : ./mvnw clean test

notifications:
    email: ashish.yete@gmail.com
before_install:
  - chmod +x mvnw 
after_success: 
    - docker build -t ashishyete/dockerDemo
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ashishyete/dockerDemo
