sudo: required
services : 
  - docker 

before_install :
  - docker build -t ashishyete/dockerDemo -f Dockerfile .
  
language : java
jdk :
   -openjdk8
script: ./mvnw clean install

jobs: 
   include:
     - stage : test
       script : ./mvnw clean test

notifications:
    email: ashish.yete@gmail.com
before_install:
  - chmod +x mvnw 