INSERT INTO BOOKS(BOOK_ID,BOOK_NAME,BOOK_DESC) VALUES (1001,'JAVA','JAVA FOR DUMMIES');
INSERT INTO BOOKS(BOOK_ID,BOOK_NAME,BOOK_DESC) VALUES (1002,'DOTNET','DOTNET FOR DUMMIES');
INSERT INTO BOOKS(BOOK_ID,BOOK_NAME,BOOK_DESC) VALUES (1003,'PYTHON','PYTHON FOR DUMMIES');
INSERT INTO BOOKS(BOOK_ID,BOOK_NAME,BOOK_DESC) VALUES (1004,'KOTLIN','KOTLIN FOR DUMMIES');
INSERT INTO BOOKS(BOOK_ID,BOOK_NAME,BOOK_DESC) VALUES (1005,'C','C FOR DUMMIES');